services:
  stats-server:
    container_name: ewm_statistics
    build:
      context: ./explore-with-me-statistics-service/explore-with-me-statistics-api
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      'spring.datasource.username': postgres
      'spring.datasource.password': postgres
      'spring.datasource.url': jdbc:postgresql://stats-db:5432/ewm_statistics

  stats-db:
    container_name: ewm_statistics_db
    image: postgres:16.1
    ports:
      - "6666:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ewm_statistics

  ewm-service:
    container_name: ewm_service
    build:
      context: ./explore-with-me-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      'spring.datasource.username': postgres
      'spring.datasource.password': postgres
      'spring.datasource.url': jdbc:postgresql://ewm-db:5432/ewm?currentSchema=ewm_service
      'statistics.server.url': http://stats-server:9090

  ewm-db:
    container_name: ewm_service_db
    image: postgres:16.1
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  ewm-kafka:
    container_name: ewm_kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"