apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-explore-with-me-stats-deployment-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-explore-with-me-stats-deployment-name
  template:
    metadata:
      labels:
        app: java-explore-with-me-stats-deployment-name
    spec:
      containers:
        - name: java-explore-with-me-stats-deployment-name-cont-name
          image: java-explore-with-me-stats-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "ewm-stats-db-service-name"

---
apiVersion: v1
kind: Service
metadata:
  name: java-explore-with-me-stats-service-name
spec:
  type: NodePort
  selector:
    app: java-explore-with-me-stats-deployment-name
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
      protocol: TCP