apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-explore-with-me-deployment-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-explore-with-me-deployment-name
  template:
    metadata:
      labels:
        app: java-explore-with-me-deployment-name
    spec:
      containers:
        - name: java-explore-with-me-deployment-name-cont-name
          image: java-explore-with-me-ewm-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "ewm-db-service-name"

---
apiVersion: v1
kind: Service
metadata:
  name: java-explore-with-me-service-name
spec:
  type: NodePort
  selector:
    app: java-explore-with-me-deployment-name
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP