CREATE TYPE participation_request_status AS ENUM (
    'PENDING',
    'REJECTED',
    'CANCELED',
    'CONFIRMED'
    );

CREATE TABLE participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT REFERENCES event (id),
    requester_id BIGINT REFERENCES users (id),
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       participation_request_status
);

CREATE CAST ( VARCHAR AS participation_request_status ) WITH INOUT AS IMPLICIT;