CREATE TYPE event_state AS ENUM (
    'PENDING',
    'CANCELED',
    'PUBLISHED'
    );

CREATE TABLE event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000) CHECK ( LENGTH(annotation) BETWEEN 20 AND 2000),
    category_id        BIGINT REFERENCES category (id),
    confirmed_requests INTEGER,
    description        VARCHAR(7000) CHECK ( LENGTH(description) BETWEEN 20 AND 7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator_id       BIGINT REFERENCES users (id),
    latitude           DOUBLE PRECISION,
    longitude          DOUBLE PRECISION,
    paid               BOOLEAN,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              event_state,
    title              VARCHAR(255) CHECK ( LENGTH(title) BETWEEN 3 AND 120),
    views              BIGINT,
    created            TIMESTAMP WITHOUT TIME ZONE
);

CREATE CAST ( VARCHAR AS event_state ) WITH INOUT AS IMPLICIT;