CREATE TYPE feedback AS ENUM ('LIKE', 'DISLIKE');

CREATE CAST (varchar AS feedback) WITH INOUT AS IMPLICIT;

CREATE TABLE rate
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES event(id),
    user_id BIGINT REFERENCES users(id),
    feedback feedback,
    created TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT only_one_feedback UNIQUE(event_id, user_id)
);
