CREATE TYPE participation_request_status AS ENUM (
    'PENDING',
    'REJECTED',
    'APPROVED'
    );

CREATE TABLE participation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES event(id),
    requester_id BIGINT REFERENCES users(id),
    created TIMESTAMP WITHOUT TIME ZONE,
    status participation_request_status
);
