CREATE TABLE users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(254) CHECK ( LENGTH(name) >= 2 AND LENGTH(name) < 251 ),
    email   VARCHAR(254) UNIQUE CHECK ( LENGTH(email) > 5 AND LENGTH(email) < 255 ),
    created TIMESTAMP WITHOUT TIME ZONE
);


CREATE TABLE category
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) UNIQUE CHECK ( LENGTH(name) > 0 AND LENGTH(name) < 51 ),
    created TIMESTAMP WITHOUT TIME ZONE
);


CREATE TABLE compilation
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned  BOOLEAN,
    title   VARCHAR(50) CHECK ( LENGTH(title) > 0 AND LENGTH(title) < 51 ),
    created TIMESTAMP WITHOUT TIME ZONE
);


CREATE TYPE event_state AS ENUM (
    'PENDING',
    'CANCELED',
    'PUBLISHED'
    );

CREATE TABLE event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000) CHECK ( LENGTH(annotation) BETWEEN 20 AND 2000),
    category_id        BIGINT REFERENCES category (id),
    confirmed_requests INTEGER,
    description        VARCHAR(7000) CHECK ( LENGTH(description) BETWEEN 20 AND 7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator_id       BIGINT REFERENCES users (id),
    latitude           DOUBLE PRECISION,
    longitude          DOUBLE PRECISION,
    paid               BOOLEAN,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              event_state,
    title              VARCHAR(255) CHECK ( LENGTH(title) BETWEEN 3 AND 120),
    views              BIGINT,
    created            TIMESTAMP WITHOUT TIME ZONE
);

CREATE CAST ( VARCHAR AS event_state ) WITH INOUT AS IMPLICIT;


CREATE TABLE compilation_event
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilations_id BIGINT GENERATED BY DEFAULT AS IDENTITY REFERENCES compilation(id),
    events_id       BIGINT GENERATED BY DEFAULT AS IDENTITY REFERENCES event(id)
);


CREATE TYPE participation_request_status AS ENUM (
    'PENDING',
    'REJECTED',
    'CANCELED',
    'CONFIRMED'
    );

CREATE TABLE participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT REFERENCES event (id),
    requester_id BIGINT REFERENCES users (id),
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       participation_request_status
);

CREATE CAST ( VARCHAR AS participation_request_status ) WITH INOUT AS IMPLICIT;